### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by taitruong** [larry0x/cw-plus-plus#13]
Hi, it should be `QueryMsg` and not `ExecuteMsg`: https://github.com/larry0x/cw-plus-plus/blame/main/packages/ownable/README.md#L97

**Comment by taitruong** [comment]
Also here: https://github.com/larry0x/cw-plus-plus/blob/main/packages/ownable/derive/src/lib.rs#L124

**Comment by shanev** [comment]
Hi @taitruong mind submitting these as PRs?

**Comment by taitruong** [comment]
Done: https://github.com/larry0x/cw-plus-plus/pull/14

**Comment by larry0x** [comment]
Merged #14
