### ISSUE TITLE
Replace `DepsMut`, instead use `Storage` and `Api`

### ISSUE THREAD

**Issue by taitruong** [larry0x/cw-plus-plus#16]
In the lib at several places, `Storage` and `Api` is being used. Except here, `transfer_ownership()`:

https://github.com/larry0x/cw-plus-plus/blob/a5007575c6b698b5aeab5743439119bb9a987960/packages/ownable/src/lib.rs#L207-L241

As a consequence this could also be remove here, `update_ownership()`:
https://github.com/larry0x/cw-plus-plus/blob/a5007575c6b698b5aeab5743439119bb9a987960/packages/ownable/src/lib.rs#L136-L150

NB: @larry0x , I could create a PR if u like too. Just let me know. I have created some other issues and PRs here, but haven't get feedback yet. So I just wait for feedback. Thx.

**Comment by larry0x** [comment]
@taitruong thanks, will check this later. For some reason I didn't get email notifications of your earlier issues/PRs. This is the first one I get a notification because you tagged my ID.

**Comment by larry0x** [comment]
The general princple I follow is that if only `api` is used, then the function takes only `deps.api`; if only `storage` is used, then the function takes only `deps.storage`; if only `querier` is used, then the function takes only `deps.querier`. However, if more than one of these is used, the contract takes `deps`, which is the case for `transfer_ownership`.
