### ISSUE TITLE
Queries?

### ISSUE THREAD

**Issue by PFC-developer** [larry0x/cw-plus-plus#3]
more a feature request than a issue.
but wouldn't you want to put in a query so you can see the info?

**Comment by larry0x** [comment]
@PFC-developer can you elaborate, query of what info?

**Comment by PFC-developer** [comment]
The ownership structure.
Wouldn't it be useful to also have a query to show the new & pending owner in contracts that can be added in a similar way to how you add the exec types ?

**Comment by larry0x** [comment]
I did not include a query method initially because for my own use case, I have a `config` query instead which includes both the ownership info and other stuff, and this "other stuff" varies by contracts.

But yeah a query method can be useful. I will add it.
