### ISSUE TITLE
More ownable improvements

### ISSUE THREAD

**Issue by 0xekez** [larry0x/cw-plus-plus#6]
1. Lets add a `cw_ownable_query` macro which adds a `#[returns(Ownership<Addr>)] Ownership {}` variant to an enum for queries.
2. Taking advantage of the fact that those macros standardize the interface we can then write a macro which generates a standard set of tests for any contract that uses the library.

**Comment by 0xekez** [comment]
`initialize_owner` should also take an `Option<&str>` instead of `owner: &str` to reflect the fact that owners are optional.

**Comment by larry0x** [comment]
> Lets add a cw_ownable_query macro

This has been implemented in #8. However, I choose `Ownership<String>` instead of `Ownership<Addr>` as the response type based on the idea that contract APIs (i.e. messages and query responses) should only contain unverified types. `Addr` represents a verified address.
